# Copyright (c) 2025-now Institut des Géosciences de l'Environnement, France.
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# Image providing a GNU/Linux environment for using Ruff on Python code.
#
# This image provides the Ruff executable, but also emacs and vim, both
# configured to auto-format Python code with Ruff on save.
#
FROM docker.io/library/fedora:latest
ARG dir_config=/xdg_config_home
COPY --chmod=400 emacs_ruff-auto-format.el $dir_config/
RUN <<EOF
dnf -y install emacs ruff
EOF
