# Copyright (c) 2025-now Institut des Géosciences de l'Environnement, France.
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# Image providing a GNU/Linux Python environment suitable for geoscience.
#
# To run a Python script with podman through a container based on this image:
#
# podman run --rm \
#     $tag_of_the_image \
#     /bin/bash -c \
#     "source /python-geoscience/venv/bin/activate ; python3 $the_script.py"
#
FROM registry.access.redhat.com/ubi8/ubi:8.10
ARG dir_python=/python-geoscience
COPY --chmod=400 requirements.txt $dir_python/
COPY --chmod=400 download-cartopy-data.py $dir_python/
RUN <<EOF
dnf -y install python3.12 python3.12-tkinter python3.12-devel python3.12-pip gcc-c++
python3 -m venv $dir_python/venv
source $dir_python/venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r $dir_python/requirements.txt
python3 $dir_python/download-cartopy-data.py
EOF
