# Copyright (c) 2025-now Institut des Géosciences de l'Environnement, France.
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# Image providing a GNU/Linux Python environment suitable for geoscience.
#
# To run a Python script with podman through a container based on this image:
#
# podman run --rm \
#     $tag_of_the_image \
#     /bin/bash -c \
#     "source /python-geoscience/venv/bin/activate ; python3 $the_script.py"
#
FROM registry.access.redhat.com/ubi9/ubi
ARG dir_python=/python-geoscience
COPY --chmod=400 requirements.txt $dir_python/
COPY --chmod=400 download-cartopy-data.py $dir_python/
COPY --chmod=400 siteconfig_cartopy.py $dir_python/
RUN <<EOF
dnf -y update
dnf -y install \
       python3.14 \
       python3.14-tkinter \
       python3.14-devel \
       python3.14-pip \
       gcc-c++ \
       gcc-gfortran
python3.14 -m venv $dir_python/venv
source $dir_python/venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r $dir_python/requirements.txt
mv $dir_python/siteconfig_cartopy.py $dir_python/venv/lib/python3.14/site-packages/cartopy/siteconfig.py
python3 $dir_python/download-cartopy-data.py
EOF
